#This is to create a makefile

all:
	g++ drive_simulator.cc simulator.cc updates.cc models.cc initializers.cc outputs.cc  -o drive_simulator

debug1:
	g++ -g drive_simulator.cc simulator.cc updates.cc models.cc initializers.cc outputs.cc  -o drive_simulator

clean:
	rm -rf drive_simulator *.o
